micronaut:
  application:
    name: event-service
  server:
    port: 9091
  # security:
  #   enabled: true
  #   endpoints:
  #     login:
  #       enabled: true
  #     oauth:
  #       enabled: true
  #   token:
  #     jwt:
  #       enabled: true
  #       signatures:
  #         secret:
  #           generator:
  #             secret: pleaseChangeThisSecretForANewOne
datasources:
  default:
    url: jdbc:postgresql://localhost:26257/eventreligi
    driverClassName: org.postgresql.Driver
    username: root
    password: root
jpa:
  default:
    packages-to-scan:
      - 'praxis.religi.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        jdbc:
          time_zone: Asia/Bangkok